fix(lv_api_map_v9_1):  fix compilation error
4 CI/CD checks issued this error:
  Error: /home/runner/work/lvgl/lvgl/src/draw/vg_lite/../../..
  /src/lv_api_map_v9_1.h:30:13: error: ‘lv_calendar_set_showed_date’
  defined but not used [-Werror=unused-function]

This commit should resolve them.