feat(vg_lite): enable warning to unused-parameter to vg-lite simulator
/home/neo/projects/lvgl/lv_port_pc_eclipse/lvgl/src/others/vg_lite_tvg/vg_lite_tvg.cpp: In function ‘vg_lite_error_t vg_lite_draw_radial_grad(vg_lite_buffer_t*, vg_lite_path_t*, vg_lite_fill_t, vg_lite_matrix_t*, vg_lite_radial_gradient_t*, vg_lite_color_t, vg_lite_blend_t, vg_lite_filter_t)’:
/home/neo/projects/lvgl/lv_port_pc_eclipse/lvgl/src/others/vg_lite_tvg/vg_lite_tvg.cpp:1738:62: error: unused parameter ‘paint_color’ [-Werror=unused-parameter]
 1738 |                                              vg_lite_color_t paint_color,
      |                                              ~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/neo/projects/lvgl/lv_port_pc_eclipse/lvgl/src/others/vg_lite_tvg/vg_lite_tvg.cpp:1740:63: error: unused parameter ‘filter’ [-Werror=unused-parameter]
 1740 |                                              vg_lite_filter_t filter)
      |                                              ~~~~~~~~~~~~~~~~~^~~~~~

Signed-off-by: Xu Xingliang <xuxingliang@xiaomi.com>