fix(draw): Fix unused function warning
Building with clang and -Wunused-function gives the following warning:

src/draw/lv_draw.c:37:24: error: unused function
'get_layer_size_kb' [-Werror,-Wunused-function]
static inline uint32_t get_layer_size_kb(uint32_t size_byte)
                       ^

get_layer_size_kb is only used from the LV_LOG_LEVEL_INFO macro, so only
include it if the log level is set to INFO or lower.

Signed-off-by: Tom Hughes <tomhughes@chromium.org>