fix(qrcodegen): fix coding style/build error
The way the brackets around this if-else are structured doesn't look
broken but it causes the following build error on some compilers (first
observed on arm-zephyr-eabi-gcc (crosstool-NG 1.24.0.378_e011758) 10.3.0):

./src/extra/libs/qrcode/qrcodegen.c:953:2: error: 'else' without a previous 'if'
  953 |  else if (assignVal < (1 << 7)) {
      |  ^~~~

Fix it by placing brackets consistently.