lv_theme_mono: fix runtime error with spinner widget using mono theme (#2202)
When using the spinner widget with the mono theme, a runtime error
occurs when the widget is styled:

Warn: Invalid style (local variable or not initialized?)
(lv_style.c #952 lv_debug_check_style())
Error: _lv_style_list_add_style         (lv_style.c #189
_lv_style_list_add_style())
Error: Invalid style (0x000055CF3A53A190)       (lv_debug.c #127
lv_debug_log_error())

This is apparently due to styles->tick_line not being initialized.

The spinner uses the arc's styles in the material theme, so the same
approach is applied here.