Revert "Let animation control enum refers to each other" It breaks build with circular dependencies, see here: ``` In file included from ../../lib/lv_bindings/lvgl/src/extra/libs/rlottie/../../../../src/extra/widgets/lv_widgets.h:34,                  from ../../lib/lv_bindings/lvgl/src/extra/libs/rlottie/../../../../lvgl.h:70,                  from ../../lib/lv_bindings/lvgl/src/extra/libs/rlottie/../../../lvgl.h:17,                  from ../../lib/lv_bindings/lvgl/src/extra/libs/rlottie/lv_rlottie.h:16,                  from ../../lib/lv_bindings/lvgl/src/extra/libs/rlottie/lv_rlottie.c:9: Error: ../../lib/lv_bindings/lvgl/src/extra/libs/rlottie/../../../../src/extra/widgets/animbtn/lv_animbtn.h:35:32: error: ‘LV_RLOTTIE_CTRL_FORWARD’ undeclared here (not in a function)    35 |     LV_ANIMBTN_CTRL_FORWARD  = LV_RLOTTIE_CTRL_FORWARD, ```
This reverts commit 94418f20368ee1382c5eb8726dbac5bbf4dd0c7c.